# Generated by Django 4.2.1 on 2023-05-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appreservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='registropordia',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
